name: Run Automated Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    # 1. Obtener el cÃ³digo
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Instalar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # 3. Instalar dependencias
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # 4. Instalar Chrome + ChromeDriver
    - name: Install Chrome & ChromeDriver
      uses: browser-actions/setup-chrome@v1

    # 5. Crear carpetas necesarias
    - name: Create reports, screenshots & logs folders
      run: |
        mkdir -p reports
        mkdir -p screenshots
        mkdir -p logs

    # 6. Forzar modo HEADLESS
    - name: Set headless mode
      run: echo "HEADLESS=true" >> $GITHUB_ENV

    # 7. Ejecutar Pytest
    - name: Run pytest
      run: |
        pytest --html=reports/report.html --self-contained-html

    # 8. Reporte HTML
    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: reports/report.html

    # 9. Screenshots
    - name: Upload screenshots
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: screenshots/

    # 10. Logs
    - name: Upload logs
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: logs/
